<div class="deepzoom">
    <?php
    $_product = $this->getProduct();
    if ($_product->getImage() == 'no_selection' || !$_product->getImage()) {
        echo '<div class="no-selection">';
        $_helper = $this->helper('catalog/output');
        $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        echo '</div>';
    } else {
        echo '<div id="deepzoom_container"></div>';
    }
    ?>
    <script type="text/javascript">
        Seadragon.Config.imagePath="<?php echo $this->getSkinUrl('images/mygento/deepzoom/') ?>";
        var viewer=null;
	
        function init()
        {viewer = new Seadragon.Viewer("deepzoom_container");viewer.openDzi("<?php echo $this->helper('mygento_deepzoom')->loadImage($_product->getImage()); ?>");}
	
        function switchTo(event,dzi)
        {if(dzi){viewer.openDzi(dzi);}else{viewer.close();}Seadragon.Utils.cancelEvent(event);}
	
        Seadragon.Utils.addEvent(window,"load",init);
    </script>
<?php if (count($this->getGalleryImages()) > 0) { ?>
        <div class="more-views">
            <h2><?php echo $this->__('More Views') ?></h2>
            <ul>
    <?php foreach ($this->getGalleryImages() as $_image) { ?>
                    <li>
                       <a href="#" onclick="
                        switchTo(event,'<?php echo $this->helper('mygento_deepzoom')->loadImage($_image->getFile()); ?>');" title="<?php echo $this->htmlEscape($_image->getLabel()) ?>">
                            <img src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(56); ?>" width="56" height="56" alt="<?php echo $this->htmlEscape($_image->getLabel()) ?>" />
                        </a>
                    </li>
    <?php } ?>
            </ul>
        </div>
<?php } ?>
</div>